const RobuxBadgeType = {
	VIRTUAL_ITEM: "VIRTUAL_ITEM",
	UPDATE: "UPDATE",
	PERSONALIZED_BONUS_ITEMS: "PERSONALIZED_BONUS_ITEMS",
	BONUS_AVATAR_ITEM: "BONUS_AVATAR_ITEM",
	MULTI_BONUS_AVATAR_ITEMS: "MULTI_BONUS_AVATAR_ITEMS",
};

export default RobuxBadgeType;
