export enum ConsentName {
	phoneNumberDiscoverabilitySetting = "phoneNumberDiscoverabilitySetting",
	phoneNumberDiscoverabilitySettingParentSide = "phoneNumberDiscoverabilitySettingParentSide",
	phoneNumberDiscoverabilityUpsell = "phoneNumberDiscoverabilityUpsell",
	personalizedAdsSetting = "personalizedAdsSetting",
	sellShareDataSetting = "sellShareDataSetting",
	allowMarketingEmailCheckboxEmailVerification = "allowMarketingEmailCheckboxEmailVerification",
	voiceDataConsentSetting = "voiceDataConsentSetting",
	voiceDataConsentSettingParentSide = "voiceDataConsentSettingParentSide",
	whoCanPartyWithMe = "whoCanPartyWithMe",
	whoCanPartyWithMeParentSide = "whoCanPartyWithMeParentSide",
	whoCanUsePartyChatWithMe = "whoCanUsePartyChatWithMe",
	whoCanUsePartyChatWithMeParentSide = "whoCanUsePartyChatWithMeParentSide",
	whoCanUsePartyVoiceWithMe = "whoCanUsePartyVoiceWithMe",
	whoCanUsePartyVoiceWithMeParentSide = "whoCanUsePartyVoiceWithMeParentSide",
	allowMarketingEmailNotifications = "allowMarketingEmailNotifications",
	receiveRobuxTransferConsentCard = "receiveRobuxTransferConsentCard",
	sendRobuxTransferConsentCard = "sendRobuxTransferConsentCard",
	vpcRequestLinkSubjectToPC = "vpcRequestLinkSubjectToPC",
	vpcRequestLinkNotSubjectToPC = "vpcRequestLinkNotSubjectToPC",
	vpcRequestLinkDefault = "vpcRequestLinkDefault",
	consentCenterAllowAction = "consentCenterAllowAction",
	consentCenterUpdateSettingNoValue = "consentCenterUpdateSettingNoValue",
	consentCenterUpdateSettingWithValue = "consentCenterUpdateSettingWithValue",
}

export default ConsentName;
